### ISSUE TITLE
~/.cache/gopass/gpg-binary.loc is storing an absolute path to gpg, which overrides the environment $PATH

### ISSUE THREAD

**Issue by siriobalmelli** [gopasspw/gopass#1662]
### Summary

`~/.cache/gopass/gpg-binary.loc` is storing an absolute path to the `gpg` executable, which overrides the environment `$PATH`.

### Steps To Reproduce

Config file:

```yaml
---
autoclip: true
autoimport: true
cliptimeout: 45
exportkeys: true
mime: true
nocolor: false
nopager: false
notifications: true
path: /Users/[my_user_name]/.password-store
safecontent: true
mounts: {}
```

```bash
export PATH=/unusual/path/to/gnupg/bin
gopass  my-password  # this works
mv /unusual/path/to/gnupg/bin /unusual/path2/to/gnupg/bin
export PATH=/unusual/path2/to/gnupg/bin
gopass  my-password  # breaks with 'Decryption failed: fork/exec /unusual/path/to/gnupg/bin/gpg'
rm ~/.cache/gopass/gpg-binary.loc
gopass  my-password  # this works again
```

### Expected behavior

Any UNIX program should *always* respect the contents of `$PATH`

### Environment

- OS: Mac OS X Catalina
- OS version: `Darwin computer.home 19.6.0 Darwin Kernel Version 19.6.0: Thu Oct 29 22:56:45 PDT 2020; root:xnu-6153.141.2.2~1/RELEASE_X86_64 x86_64 i386 MacBookPro16,1 Darwin`
- gopass Version: `gopass 1.10.1+af9c95d20b722dee331adcc3cc1ab1ce0108dc2b (af9c95d20b722dee331adcc3cc1ab1ce0108dc2b) go1.15.6 darwin amd64`
- Installation method: [Nix](https://nixos.org/), building the latest build from source
