### ISSUE TITLE
parsing is not honored in config

### ISSUE THREAD

**Issue by deadc0de6** [gopasspw/gopass#1991]
### Summary

`parsing` entry set to `false` manually in the config is not honored.

### Steps To Reproduce

Here's the config I have:
```yaml
autoimport: false
cliptimeout: 45
nopager: false
path: /home/user/password-store
safecontent: false
nocolor: false
parsing: false
mounts: {}
```

Here is what gopass says about `parsing` config entry:
```bash
$ gopass config parsing
parsing: true
```

Editing the config with gopass itself will somehow re-order the entries and result in a `parsing` entry being correctly handled:
```bash
$ gopass config parsing false
parsing: false

$ gopass config parsing
parsing: false

$ gopass config
autoclip: false
autoimport: false
cliptimeout: 45
exportkeys: false
nopager: false
notifications: false
parsing: false
path: /home/user/password-store
safecontent: false
```

### Expected behavior

`parsing` is honored independently where it is in the config file

### Environment

- OS: linux
- gopass Version: 1.12.8
