### ISSUE TITLE
gopass unable to find PGP keys when running in Github Actions

### ISSUE THREAD

**Issue by felixhammerl** [gopasspw/gopass#2872]
### Summary

I am trying to use gopass in Github Actions. 

To this end, I have a secrets store called `test-gopass-1`, which gets cloned via a Personal Access Token from inside the workflow. However, after cloning the store, gopass seems unable to find the secret key in GPG and tries to create a new key from git author settings, despite the key very clearly existing. 

The key being used is `0xF9CA7755347E6586`, belonging to `gopass-terraform-example <gopass-terraform-example@github>`.

Even stranger, if I let gopass create a random key, it can actually decrypt the secret, despite thinking it has the wrong key. If it actually tried to use the key it just created, it would not be able to read the secrets store.

The image is `ubuntu-latest`.

The key is imported through a secret called `PGP_KEY`, the PGP key ID is provided to the root store via a secret called `PGP_KEY_ID`. 

### Steps To Reproduce

Here is the action:

```
name: Pipeline
on: [push, workflow_dispatch]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2

      - name: Import GPG key
        run: echo "${{ secrets.PGP_KEY }}" | gpg --import

      - name: Check version and keys
        run: |
          which gpg
          gpg --version
          gpg --with-colons --with-fingerprint --fixed-list-mode --list-secret-keys
      
      - name: Install gopass
        run: wget https://github.com/gopasspw/gopass/releases/download/v1.15.8/gopass_1.15.8_linux_amd64.deb && sudo dpkg -i gopass_1.15.8_linux_amd64.deb

      - name: Initialize gopass
        run: gopass init ${{ secrets.PGP_KEY_ID }}

      - name: Set up gopass secrets store
        run: gopass clone https://${{ secrets.PERSONAL_ACCESS_TOKEN }}@github.com/felixhammerl/test-gopass-1.git test-gopass-1

      - name: Make sure gopass works
        run: gopass show test-gopass-1/dev/asdasd
```

The log output of the failing `gopass clone` execution is:

```
Run gopass clone https://***@github.com/felixhammerl/test-gopass-1.git test-gopass-1

   __     _    _ _      _ _   ___   ___
 /'_ '\ /'_'\ ( '_'\  /'_' )/',__)/',__)
( (_) |( (_) )| (_) )( (_| |\__, \\__, \
'\__  |'\___/'| ,__/''\__,_)(____/(____/
( )_) |       | |
 \___/'       (_)

🌟 Welcome to gopass!
🌟 Cloning an existing password store from "https://***@github.com/felixhammerl/test-gopass-1.git" ...
⚠ Cloning gitfs repository "https://***@github.com/felixhammerl/test-gopass-1.git" to "/home/runner/.local/share/gopass/stores/test-gopass-1" ...
Git Email not set
⚠ Failed to commit .gitattributes to git
git configured at /home/runner/.local/share/gopass/stores/test-gopass-1
Mounted password store /home/runner/.local/share/gopass/stores/test-gopass-1 at mount point `test-gopass-1` ...
⚠ Configuring gitfs repository ...
🎩 Gathering information for the git repository ...
Git Email not set
⚠ Failed to commit .gitattributes to git
Your password store is ready to use! Have a look around: `gopass list test-gopass-1`

🔐 No useable cryptographic keys. Generating new key pair
🧪 Creating cryptographic key pair (gpg) ...
🎩 Gathering information for the gpg key pair ...
202[4](https://github.com/felixhammerl/gopass-terraform-example/actions/runs/8839616052/job/24273348191#step:7:5)/04/2[5](https://github.com/felixhammerl/gopass-terraform-example/actions/runs/8839616052/job/24273348191#step:7:6) 21:28:12 failed to create new private key: failed to create new private key: failed to run command: '/usr/bin/gpg [/usr/bin/gpg --batch --gen-key]': "gpg: Generating a RSA/RSA key pair\ngpg: -:[8](https://github.com/felixhammerl/gopass-terraform-example/actions/runs/8839616052/job/24273348191#step:7:9): missing argument\n" - exit status 2
```

### Environment

- OS: Ubuntu
- OS version: 22.0.4
- gopass Version: `gopass_1.15.8_linux_amd64.deb`
- Installation method: `wget https://github.com/gopasspw/gopass/releases/download/v1.15.8/gopass_1.15.8_linux_amd64.deb && sudo dpkg -i gopass_1.15.8_linux_amd64.deb`
- `which gpg`: `/usr/bin/gpg`

`gpg --version`: 

```
shell: /usr/bin/bash -e {0}
/usr/bin/gpg
gpg (GnuPG) 2.2.27
libgcrypt 1.9.4
Copyright (C) 2021 Free Software Foundation, Inc.
License GNU GPL-3.0-or-later <https://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

Home: /home/runner/.gnupg
Supported algorithms:
Pubkey: RSA, ELG, DSA, ECDH, ECDSA, EDDSA
Cipher: IDEA, 3DES, CAST5, BLOWFISH, AES, AES192, AES25[6](https://github.com/felixhammerl/gopass-terraform-example/actions/runs/8839616052/job/24273348191#step:4:7), TWOFISH,
        CAMELLIA128, CAMELLIA192, CAMELLIA256
Hash: SHA1, RIPEMD160, SHA256, SHA3[8](https://github.com/felixhammerl/gopass-terraform-example/actions/runs/8839616052/job/24273348191#step:4:9)4, SHA512, SHA224
Compression: Uncompressed, ZIP, ZLIB, BZIP2
```

`gpg --with-colons --with-fingerprint --fixed-list-mode --list-secret-keys`:

```
sec:-:255:22:F9CA7755347E6586:1714038690:1808646690::-:::scESC:::+::ed25519:::0:
fpr:::::::::0BD7A9CD3879692AC798DB37F9CA7755347E6586:
grp:::::::::7E618A5619E3D85845A461CC2E9A17A825056261:
uid:-::::1714038690::6D88BAC39B2EE34C38E[23](https://github.com/felixhammerl/gopass-terraform-example/actions/runs/8839616052/job/24273348191#step:4:24)D4059C5811A8C1E250B::gopass-terraform-example <gopass-terraform-example@github>::::::::::0:
ssb:-:255:18:34450B171B299CBB:1714038690:1808646690:::::e:::+::cv25519::
fpr:::::::::5E61279E484710460AC60C5234450B171B299CBB:
grp:::::::::421853EE087F62980288FF2D84C3078AAE6048B7:
```

Please let me know if you would like the debug logs
